// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5s7v37lKoO1PCk2b-VT4n925-eWvfBw',
    appId: '1:1041923972249:web:1ecf586bb790859a802c08',
    messagingSenderId: '1041923972249',
    projectId: 'eshick-e5c72',
    authDomain: 'eshick-e5c72.firebaseapp.com',
    storageBucket: 'eshick-e5c72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1exfP5Aae48p6FCc-ZL0jBMjq9-AAug',
    appId: '1:1041923972249:android:cb0f68f123703e39802c08',
    messagingSenderId: '1041923972249',
    projectId: 'eshick-e5c72',
    storageBucket: 'eshick-e5c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSoCtd9eWjaDxYLuaCBIBsKvMcNbvXAk',
    appId: '1:1041923972249:ios:57d10625c0c011dd802c08',
    messagingSenderId: '1041923972249',
    projectId: 'eshick-e5c72',
    storageBucket: 'eshick-e5c72.appspot.com',
    androidClientId: '1041923972249-jl5vs1nahck6vi6vjqre6s4av3meo936.apps.googleusercontent.com',
    iosClientId: '1041923972249-teqf5h2m9leq325p4hb9copbi1jphtth.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}